<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';
require_once dirname(__DIR__) . '/libs/sfm_debug_public_lib.php';
sfm_debug_public_headers();
$token=(string)($_GET['token']??($_SERVER['PATH_INFO']??'')); $token=trim($token,'/'); sfm_debug_public_rate_limit($token); $link=sfm_debug_public_validate($dbcnx,$token,true);
function h($s): string { return htmlspecialchars((string)$s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
function file_url(string $token,int $pid,string $type,string $file=''): string { return '/debug_share_file.php?token='.rawurlencode($token).'&pipeline_run_id='.$pid.'&artifact_type='.rawurlencode($type).($file!==''?'&file_id='.rawurlencode($file):''); }
$sid=(int)$link['capture_session_id']; $oid=(int)$link['order_id']; $base=sfm_debug_public_session_base($link); $videoDir=$base.'/videos';
$videos=[]; if(is_dir($videoDir)){ foreach(glob($videoDir.'/*.mp4')?:[] as $v){ $videos[]=['filename'=>basename($v),'size'=>filesize($v),'mtime'=>date('Y-m-d H:i:s',filemtime($v))]; } }
$runs=[]; $st=$dbcnx->prepare('SELECT * FROM sfm_pipeline_runs WHERE capture_session_id=? ORDER BY id DESC'); if($st){$st->bind_param('i',$sid);$st->execute();$rs=$st->get_result();while($r=$rs->fetch_assoc())$runs[]=$r;$st->close();}
$photoCount=0; $st=$dbcnx->prepare('SELECT COUNT(*) c FROM photo_points WHERE session_id=? AND deleted_at IS NULL'); if($st){$st->bind_param('i',$sid);$st->execute();$photoCount=(int)($st->get_result()->fetch_assoc()['c']??0);$st->close();}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Debug public link</title><style>body{font-family:Arial,sans-serif;margin:24px}.card{border:1px solid #ddd;border-radius:8px;padding:16px;margin:12px 0}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:6px;text-align:left}code,pre{background:#f6f6f6;padding:2px 4px}.grid{display:flex;gap:8px;flex-wrap:wrap}.btn{display:inline-block;padding:6px 10px;border:1px solid #777;border-radius:4px;text-decoration:none;margin:2px}</style></head><body>
<h1>Debug public link</h1>
<div class="card"><h2>Session summary</h2><table><tr><th>order_id</th><td><?=h($oid)?></td></tr><tr><th>capture_session_id</th><td><?=h($sid)?></td></tr><tr><th>app_session_uuid</th><td><?=h($link['app_session_uuid'])?></td></tr><tr><th>created_at</th><td><?=h($link['session_created_at'])?></td></tr><tr><th>video count</th><td><?=count($videos)?></td></tr><tr><th>photo count</th><td><?=$photoCount?></td></tr><tr><th>current processing state</th><td><?=h($link['order_status'])?></td></tr></table></div>
<div class="card"><h2>Source media</h2><?php foreach($videos as $v): ?><div><b><?=h($v['filename'])?></b> <?=h($v['size'])?> bytes uploaded <?=h($v['mtime'])?><br><video width="360" controls preload="metadata" src="<?=h(file_url($token,0,'source_video',$v['filename']))?>"></video><div class="grid"><a class="btn" href="<?=h(file_url($token,0,'source_video',$v['filename']))?>">Download</a><a class="btn" href="<?=h(file_url($token,0,'camera_info',$v['filename']))?>&download=0">View camera_info</a><a class="btn" href="<?=h(file_url($token,0,'manifest',$v['filename']))?>&download=0">View manifest</a><a class="btn" href="<?=h(file_url($token,0,'imu',$v['filename']))?>">Download IMU</a></div></div><?php endforeach; ?></div>
<div class="card"><h2>Pipeline runs</h2><table><tr><th>pipeline_run_id</th><th>mode</th><th>status</th><th>stage</th><th>started</th><th>finished</th><th>registration</th><th>dense points</th><th>mesh</th><th>actions</th></tr><?php foreach($runs as $r): $pid=(int)$r['id']; ?><tr><td><?=$pid?></td><td><?=h($r['pipeline_mode'])?></td><td><?=h($r['status'])?></td><td><?=h($r['stage'])?></td><td><?=h($r['started_at'])?></td><td><?=h($r['finished_at'])?></td><td><?=h($r['registration_ratio'])?></td><td><?=h($r['dense_points'])?></td><td><?=h(($r['mesh_vertices']??'').'/'.($r['mesh_faces']??''))?></td><td><a class="btn" href="/sfm_3d_viewer.php?debug_token=<?=h(rawurlencode($token))?>&pipeline_run_id=<?=$pid?>&artifact=dense">Dense viewer</a><a class="btn" href="/sfm_3d_viewer.php?debug_token=<?=h(rawurlencode($token))?>&pipeline_run_id=<?=$pid?>&artifact=mesh">Mesh viewer</a></td></tr><?php endforeach; ?></table></div>
<div class="card"><h2>Frame selection</h2><?php foreach($runs as $r): $pid=(int)$r['id']; ?><h3>Run <?=$pid?></h3><div class="grid"><a class="btn" href="<?=h(file_url($token,$pid,'selected_frames'))?>&download=0">selected_frames.json</a><a class="btn" href="<?=h(file_url($token,$pid,'quality_summary'))?>&download=0">quality_summary.json</a><a class="btn" href="<?=h(file_url($token,$pid,'frame_quality'))?>&download=0">frame_quality.json</a><a class="btn" href="<?=h(file_url($token,$pid,'rejected_frames'))?>&download=0">rejected_frames.json</a></div><?php endforeach; ?></div>
<div class="card"><h2>Sparse diagnostics / Dense point clouds / Meshes / Logs</h2><?php foreach($runs as $r): $pid=(int)$r['id']; ?><h3>Run <?=$pid?></h3><div class="grid"><a class="btn" href="<?=h(file_url($token,$pid,'sparse_diagnostics'))?>&download=0">Open diagnostics</a><a class="btn" href="<?=h(file_url($token,$pid,'sparse_ply'))?>">Sparse point cloud</a><a class="btn" href="<?=h(file_url($token,$pid,'dense_ply'))?>">Dense point cloud</a><a class="btn" href="<?=h(file_url($token,$pid,'mesh_ply'))?>">Final mesh</a><a class="btn" href="<?=h(file_url($token,$pid,'mesh_stats'))?>&download=0">Mesh stats</a><a class="btn" href="<?=h(file_url($token,$pid,'pipeline_result'))?>&download=0">Pipeline result JSON</a><a class="btn" href="<?=h(file_url($token,$pid,'pipeline_log'))?>&download=0">View log</a><a class="btn" href="<?=h(file_url($token,$pid,'full_log'))?>">Download full log</a></div><?php endforeach; ?></div>
<div class="card"><h2>Download debug bundle</h2><a class="btn" href="<?=h(file_url($token,0,'debug_bundle'))?>">Download debug bundle</a></div>
</body></html>