<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';
require_once dirname(__DIR__) . '/libs/sfm_debug_public_lib.php';
sfm_debug_public_headers();
$token=(string)($_GET['token']??($_SERVER['PATH_INFO']??'')); $token=trim($token,'/'); sfm_debug_public_rate_limit($token); $link=sfm_debug_public_validate($dbcnx,$token,true);
function h($s): string { return htmlspecialchars((string)$s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
function file_url(string $token,int $pid,string $type,string $file=''): string { return '/debug_share_file.php?token='.rawurlencode($token).'&pipeline_run_id='.$pid.'&artifact_type='.rawurlencode($type).($file!==''?'&file_id='.rawurlencode($file):''); }
function artifact_link_or_na(mysqli $db, array $link, string $token, int $pid, string $type, string $label, bool $inline=false, string $fileId=''): string {
    $artifact = sfm_debug_public_artifact_path($db, $link, $pid, $type, $fileId);
    if (!$artifact) return '<span class="btn" aria-disabled="true">'.h($label).': Not available</span>';
    $url = file_url($token, $pid, $type, $fileId) . ($inline ? '&download=0' : '');
    return '<a class="btn" href="'.h($url).'">'.h($label).'</a>';
}
function viewer_link_or_na(mysqli $db, array $link, string $token, int $pid, string $artifact, string $label): string {
    $type = ['sparse'=>'sparse_ply','dense'=>'dense_ply','mesh'=>'mesh_ply'][$artifact] ?? '';
    if ($type === '' || !sfm_debug_public_artifact_path($db, $link, $pid, $type)) return '<span class="btn" aria-disabled="true">'.h($label).': Not available</span>';
    return '<a class="btn" href="/sfm_3d_viewer.php?debug_token='.h(rawurlencode($token)).'&pipeline_run_id='.$pid.'&artifact='.h($artifact).'">'.h($label).'</a>';
}
$sid=(int)$link['capture_session_id']; $oid=(int)$link['order_id']; $base=sfm_debug_public_session_base($link); $videoDir=$base.'/videos';
$videos=[]; if(is_dir($videoDir)){ foreach(glob($videoDir.'/*.mp4')?:[] as $v){ $videos[]=['filename'=>basename($v),'size'=>filesize($v),'mtime'=>date('Y-m-d H:i:s',filemtime($v))]; } }
$runs=[]; $st=$dbcnx->prepare('SELECT * FROM sfm_pipeline_runs WHERE capture_session_id=? ORDER BY id DESC'); if($st){$st->bind_param('i',$sid);$st->execute();$rs=$st->get_result();while($r=$rs->fetch_assoc())$runs[]=$r;$st->close();}
$photoCount=0; $st=$dbcnx->prepare('SELECT COUNT(*) c FROM photo_points WHERE session_id=? AND deleted_at IS NULL'); if($st){$st->bind_param('i',$sid);$st->execute();$photoCount=(int)($st->get_result()->fetch_assoc()['c']??0);$st->close();}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Debug public link</title><style>body{font-family:Arial,sans-serif;margin:24px}.card{border:1px solid #ddd;border-radius:8px;padding:16px;margin:12px 0}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:6px;text-align:left}code,pre{background:#f6f6f6;padding:2px 4px}.grid{display:flex;gap:8px;flex-wrap:wrap}.btn{display:inline-block;padding:6px 10px;border:1px solid #777;border-radius:4px;text-decoration:none;margin:2px}</style></head><body>
<h1>Debug public link</h1>
<div class="card"><h2>Session summary</h2><table><tr><th>order_id</th><td><?=h($oid)?></td></tr><tr><th>capture_session_id</th><td><?=h($sid)?></td></tr><tr><th>app_session_uuid</th><td><?=h($link['app_session_uuid'])?></td></tr><tr><th>created_at</th><td><?=h($link['session_created_at'])?></td></tr><tr><th>video count</th><td><?=count($videos)?></td></tr><tr><th>photo count</th><td><?=$photoCount?></td></tr><tr><th>current processing state</th><td><?=h($link['order_status'])?></td></tr></table></div>
<div class="card"><h2>Source media</h2><?php foreach($videos as $v): $videoArtifact=sfm_debug_public_artifact_path($dbcnx,$link,0,'source_video',$v['filename']); ?><div><b><?=h($v['filename'])?></b> <?=h($v['size'])?> bytes uploaded <?=h($v['mtime'])?><br><?php if($videoArtifact): ?><video width="360" controls preload="metadata" src="<?=h(file_url($token,0,'source_video',$v['filename']))?>"></video><?php else: ?><span class="btn" aria-disabled="true">Video: Not available</span><?php endif; ?><div class="grid"><?=artifact_link_or_na($dbcnx,$link,$token,0,'source_video','Download',false,$v['filename'])?><?=artifact_link_or_na($dbcnx,$link,$token,0,'camera_info','View camera_info',true,$v['filename'])?><?=artifact_link_or_na($dbcnx,$link,$token,0,'manifest','View manifest',true,$v['filename'])?><?=artifact_link_or_na($dbcnx,$link,$token,0,'imu','Download IMU',false,$v['filename'])?></div></div><?php endforeach; ?></div>
<div class="card"><h2>Pipeline runs</h2><table><tr><th>pipeline_run_id</th><th>mode</th><th>scope</th><th>source run</th><th>completed</th><th>status</th><th>stage</th><th>started</th><th>finished</th><th>registration</th><th>dense points</th><th>mesh</th><th>actions</th></tr><?php foreach($runs as $r): $pid=(int)$r['id']; ?><tr><td><?=$pid?></td><td><?=h($r['pipeline_mode'])?></td><td><?=h($r['run_scope']??'FULL')?></td><td><?=h($r['source_pipeline_run_id']??'')?></td><td><?=h($r['completed_stage']??'')?></td><td><?=h($r['status'])?></td><td><?=h($r['stage'])?></td><td><?=h($r['started_at'])?></td><td><?=h($r['finished_at'])?></td><td><?=h($r['registration_ratio'])?></td><td><?=h($r['dense_points'])?></td><td><?=h(($r['mesh_vertices']??'').'/'.($r['mesh_faces']??''))?></td><td><?=viewer_link_or_na($dbcnx,$link,$token,$pid,'sparse','Sparse viewer')?><?=viewer_link_or_na($dbcnx,$link,$token,$pid,'dense','Dense viewer')?><?=viewer_link_or_na($dbcnx,$link,$token,$pid,'mesh','Mesh viewer')?></td></tr><?php endforeach; ?></table></div>
<div class="card"><h2>Frame selection</h2><?php foreach($runs as $r): $pid=(int)$r['id']; ?><h3>Run <?=$pid?></h3><div class="grid"><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'selected_frames','selected_frames.json',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'quality_summary','quality_summary.json',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'frame_quality','frame_quality.json',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'rejected_frames','rejected_frames.json',true)?></div><?php endforeach; ?></div>
<div class="card"><h2>Sparse diagnostics / Dense point clouds / Meshes / Logs</h2><?php foreach($runs as $r): $pid=(int)$r['id']; ?><h3>Run <?=$pid?></h3><div class="grid"><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'sparse_diagnostics','Open diagnostics',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'camera_trajectory','Camera trajectory',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'world_alignment','World alignment',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'sparse_ply','Sparse point cloud')?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'dense_ply','Dense point cloud')?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'mesh_ply','Final mesh')?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'mesh_stats','Mesh stats',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'pipeline_result','Pipeline result JSON',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'pipeline_log','View log',true)?><?=artifact_link_or_na($dbcnx,$link,$token,$pid,'full_log','Download full log')?></div><?php endforeach; ?></div>
<div class="card"><h2>Download debug bundle</h2><a class="btn" href="<?=h(file_url($token,0,'debug_bundle'))?>">Download debug bundle</a></div>
</body></html>