<?php
declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';

auth_require_login();

$user = auth_current_user();
$userId = (int)$user['id'];
$role = $user['role'] ?? 'BROKER';

$path = (string)($_GET['path'] ?? '');
$path = trim($path);

if ($path === '') {
    http_response_code(400);
    exit('Missing path');
}

// Normalize URL-decoded path.
$path = str_replace('\\', '/', $path);
$path = ltrim($path, '/');

// Only storage/order media is allowed.
if (!preg_match('~^orders/([0-9]+)/~', $path, $m)) {
    http_response_code(400);
    exit('Bad media path');
}

$orderId = (int)$m[1];

function maklertour_can_view_order_media(array $order, int $userId, string $role): bool {
    return $role === 'ADMIN'
        || ((int)$order['broker_id'] === $userId)
        || (
            $role === 'OPERATOR'
            && (
                (int)$order['operator_id'] === $userId
                || (
                    (int)$order['is_published'] === 1
                    && (string)$order['status'] === 'NEW'
                    && $order['operator_id'] === null
                )
            )
        );
}

function maklertour_load_order_for_media(mysqli $dbcnx, int $orderId): ?array {
    $stmt = $dbcnx->prepare("
        SELECT *
        FROM tour_orders
        WHERE id = ?
        LIMIT 1
    ");

    if (!$stmt) {
        return null;
    }

    $stmt->bind_param('i', $orderId);
    $stmt->execute();
    $order = $stmt->get_result()->fetch_assoc() ?: null;
    $stmt->close();

    return $order;
}

$order = maklertour_load_order_for_media($dbcnx, $orderId);

if (!$order) {
    http_response_code(404);
    exit('Order not found');
}

$canView = maklertour_can_view_order_media($order, $userId, $role);

/*
 * Legacy/fallback access:
 * Older uploads may have media paths like:
 *   orders/<old_order_id>/sessions/<app_session_uuid>/...
 * while the capture_session with this app_session_uuid belongs to another order.
 *
 * In that case authorize by the real order attached to capture_sessions.app_session_uuid.
 * Do not move files here; this is access-control compatibility only.
 */
if (!$canView && preg_match('~^orders/[0-9]+/sessions/([^/]+)/~', $path, $sm)) {
    $appSessionUuid = (string)$sm[1];

    $stmt = $dbcnx->prepare("
        SELECT
            o.*
        FROM capture_sessions cs
        JOIN tour_orders o ON o.id = cs.order_id
        WHERE cs.app_session_uuid = ?
          AND cs.deleted_at IS NULL
        ORDER BY cs.id DESC
        LIMIT 1
    ");

    if ($stmt) {
        $stmt->bind_param('s', $appSessionUuid);
        $stmt->execute();
        $realOrder = $stmt->get_result()->fetch_assoc() ?: null;
        $stmt->close();

        if ($realOrder && maklertour_can_view_order_media($realOrder, $userId, $role)) {
            $canView = true;
        }
    }
}

if (!$canView) {
    http_response_code(403);
    exit('Forbidden');
}

$storageRoot = defined('APP_STORAGE_DIR')
    ? APP_STORAGE_DIR
    : dirname(__DIR__) . '/storage';

$storageRootReal = realpath($storageRoot);

if ($storageRootReal === false) {
    http_response_code(500);
    exit('Storage root missing');
}

$fullPath = $storageRootReal . '/' . $path;
$fileReal = realpath($fullPath);

if (
    $fileReal === false
    || strpos($fileReal, $storageRootReal . DIRECTORY_SEPARATOR) !== 0
    || !is_file($fileReal)
) {
    http_response_code(404);
    exit('File not found');
}

$ext = strtolower((string)pathinfo($fileReal, PATHINFO_EXTENSION));

$contentType = match ($ext) {
    'jpg', 'jpeg' => 'image/jpeg',
    'png' => 'image/png',
    'webp' => 'image/webp',
    'gif' => 'image/gif',
    'mp4' => 'video/mp4',
    'mov' => 'video/quicktime',
    default => 'application/octet-stream',
};

clearstatcache(true, $fileReal);

$size = filesize($fileReal);
if ($size === false || $size < 0) {
    http_response_code(500);
    exit('Cannot read file size');
}

$start = 0;
$end = $size - 1;
$statusCode = 200;

$rangeHeader = $_SERVER['HTTP_RANGE'] ?? '';

if ($rangeHeader !== '') {
    if (preg_match('/bytes=(\d*)-(\d*)/i', (string)$rangeHeader, $r)) {
        if ($r[1] !== '') {
            $start = (int)$r[1];
        }

        if ($r[2] !== '') {
            $end = (int)$r[2];
        }

        if ($r[1] === '' && $r[2] !== '') {
            $suffix = (int)$r[2];
            if ($suffix > 0) {
                $start = max(0, $size - $suffix);
                $end = $size - 1;
            }
        }

        if ($start > $end || $start >= $size) {
            while (ob_get_level() > 0) {
                ob_end_clean();
            }

            header('Content-Range: bytes */' . $size);
            http_response_code(416);
            exit;
        }

        $end = min($end, $size - 1);
        $statusCode = 206;
    }
}

$length = $end - $start + 1;

// Critical: remove any output generated by bootstrap/session/smarty/warnings.
// Binary media response must start exactly with file bytes.
while (ob_get_level() > 0) {
    ob_end_clean();
}

ini_set('zlib.output_compression', '0');

http_response_code($statusCode);
header('Content-Type: ' . $contentType);
header('Content-Disposition: inline; filename="' . basename($fileReal) . '"');
header('X-Content-Type-Options: nosniff');
header('Accept-Ranges: bytes');
header('Cache-Control: private, max-age=3600');
header('Content-Length: ' . $length);

if ($statusCode === 206) {
    header('Content-Range: bytes ' . $start . '-' . $end . '/' . $size);
}

if ($_SERVER['REQUEST_METHOD'] === 'HEAD') {
    exit;
}

$fp = fopen($fileReal, 'rb');
if ($fp === false) {
    http_response_code(500);
    exit;
}

if ($start > 0) {
    fseek($fp, $start);
}

$remaining = $length;

while ($remaining > 0 && !feof($fp)) {
    $read = min(1024 * 1024, $remaining);
    $buffer = fread($fp, $read);

    if ($buffer === false || $buffer === '') {
        break;
    }

    echo $buffer;
    flush();

    $remaining -= strlen($buffer);
}

fclose($fp);
exit;
