<?php
declare(strict_types=1);

function sfm_system_defaults(): array {
    return [
        'extract'=>['sampling_mode'=>'auto_quality','target_frames'=>400,'candidate_multiplier'=>1.5,'minimum_sampling_fps'=>0.25,'maximum_sampling_fps'=>10.0,'quality_filter'=>true,'scale_width'=>1920,'allow_upscale'=>false,'keep_candidate_frames'=>false,'fps'=>2.0,'max_frames'=>360,'jpeg_quality'=>2],
        'sparse'=>['matcher'=>'sequential','sequential_overlap'=>30,'loop_detection'=>false],
        'preview'=>['max_image_size'=>640,'num_src_images'=>16,'chunk_overlap'=>15,'target_images_per_chunk'=>50,'max_images_per_chunk'=>80,'mesh_depth'=>7,'target_faces'=>100000,'mesh_engine'=>'open3d','density_quantile'=>0.12,'statistical_nb_neighbors'=>24,'statistical_std_ratio'=>2.0,'radius_nb_points'=>6,'radius_multiplier'=>3.0,'crop_low_percentile'=>0.01,'crop_high_percentile'=>0.99,'minimum_component_ratio'=>0.01,'maximum_triangle_edge_multiplier'=>8.0],
        'standard'=>['max_image_size'=>1600,'num_src_images'=>20,'chunk_overlap'=>12,'target_images_per_chunk'=>40,'max_images_per_chunk'=>60,'mesh_depth'=>8,'target_faces'=>300000,'mesh_engine'=>'open3d','density_quantile'=>0.12,'statistical_nb_neighbors'=>24,'statistical_std_ratio'=>2.0,'radius_nb_points'=>6,'radius_multiplier'=>3.0,'crop_low_percentile'=>0.01,'crop_high_percentile'=>0.99,'minimum_component_ratio'=>0.01,'maximum_triangle_edge_multiplier'=>8.0],
        'fullhd'=>['max_image_size'=>1920,'num_src_images'=>20,'chunk_overlap'=>10,'target_images_per_chunk'=>30,'max_images_per_chunk'=>45,'mesh_depth'=>9,'target_faces'=>500000,'mesh_engine'=>'open3d','density_quantile'=>0.12,'statistical_nb_neighbors'=>24,'statistical_std_ratio'=>2.0,'radius_nb_points'=>6,'radius_multiplier'=>3.0,'crop_low_percentile'=>0.01,'crop_high_percentile'=>0.99,'minimum_component_ratio'=>0.01,'maximum_triangle_edge_multiplier'=>8.0],
    ];
}

function sfm_settings_json_encode(array $settings): string { return json_encode($settings, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); }
function sfm_json_array(?string $json): array { $v=json_decode((string)$json,true); return is_array($v)?$v:[]; }
function sfm_load_user_settings(mysqli $db,int $userId): array { $st=$db->prepare('SELECT settings_json FROM sfm_user_settings WHERE user_id=? LIMIT 1'); if(!$st){return [];} $st->bind_param('i',$userId); $st->execute(); $row=$st->get_result()->fetch_assoc(); $st->close(); return $row?sfm_json_array($row['settings_json']):[]; }
function sfm_save_user_settings(mysqli $db,int $userId,array $settings): void { $json=sfm_settings_json_encode(sfm_validate_settings($settings)); $st=$db->prepare('INSERT INTO sfm_user_settings (user_id,settings_json) VALUES (?,?) ON DUPLICATE KEY UPDATE settings_json=VALUES(settings_json), updated_at=NOW(6)'); if(!$st){throw new RuntimeException($db->error);} $st->bind_param('is',$userId,$json); $st->execute(); $st->close(); }
function sfm_reset_user_settings(mysqli $db,int $userId): void { $st=$db->prepare('DELETE FROM sfm_user_settings WHERE user_id=?'); if($st){$st->bind_param('i',$userId);$st->execute();$st->close();} }
function sfm_load_session_settings(mysqli $db,int $sessionId,int $userId): array { $st=$db->prepare('SELECT settings_json FROM sfm_session_settings WHERE capture_session_id=? AND user_id=? LIMIT 1'); if(!$st){return [];} $st->bind_param('ii',$sessionId,$userId); $st->execute(); $row=$st->get_result()->fetch_assoc(); $st->close(); return $row?sfm_json_array($row['settings_json']):[]; }
function sfm_save_session_settings(mysqli $db,int $sessionId,int $userId,array $settings): void { $json=sfm_settings_json_encode(sfm_validate_settings($settings)); $st=$db->prepare('INSERT INTO sfm_session_settings (capture_session_id,user_id,settings_json) VALUES (?,?,?) ON DUPLICATE KEY UPDATE settings_json=VALUES(settings_json), updated_at=NOW(6)'); if(!$st){throw new RuntimeException($db->error);} $st->bind_param('iis',$sessionId,$userId,$json); $st->execute(); $st->close(); }
function sfm_reset_session_settings(mysqli $db,int $sessionId,int $userId): void { $st=$db->prepare('DELETE FROM sfm_session_settings WHERE capture_session_id=? AND user_id=?'); if($st){$st->bind_param('ii',$sessionId,$userId);$st->execute();$st->close();} }
function sfm_merge_settings(array $system,array $user,array $session,array $request): array { return array_replace_recursive($system,$user,$session,$request); }

function sfm_validate_settings(array $settings): array {
    $defaults=sfm_system_defaults(); $out=[]; $errors=[];
    $num=function($path,$min,$max,$float=false) use ($settings,&$out,&$errors){ $parts=explode('.',$path); $v=$settings; foreach($parts as $p){ if(!is_array($v)||!array_key_exists($p,$v)){return;} $v=$v[$p]; } if(!is_numeric($v)){ $errors[$path]='must be numeric'; return; } $n=$float?(float)$v:(int)$v; if($n<$min||$n>$max){$errors[$path]="must be between {$min} and {$max}"; return;} $ref=&$out; foreach($parts as $p){ if(!isset($ref[$p])||!is_array($ref[$p])){$ref[$p]=[];} $ref=&$ref[$p]; } $ref=$n; };
    foreach(['extract.fps'=>[0.5,10,true],'extract.max_frames'=>[30,2000,false],'extract.scale_width'=>[320,3840,false],'extract.jpeg_quality'=>[1,31,false],'extract.target_frames'=>[30,5000,false],'extract.candidate_multiplier'=>[1,5,true],'extract.minimum_sampling_fps'=>[0.01,30,true],'extract.maximum_sampling_fps'=>[0.1,60,true],'sparse.sequential_overlap'=>[5,100,false]] as $p=>$r){$num($p,$r[0],$r[1],$r[2]);}
    if(isset($settings['extract']['sampling_mode'])){ if(in_array($settings['extract']['sampling_mode'],['auto_quality','auto_uniform','manual'],true)){$out['extract']['sampling_mode']=$settings['extract']['sampling_mode'];} else {$errors['extract.sampling_mode']='unsupported value';} }
    foreach(['quality_filter','allow_upscale','keep_candidate_frames'] as $b){ if(isset($settings['extract'][$b])){$out['extract'][$b]=filter_var($settings['extract'][$b],FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE)??false;} }
    if(isset($settings['sparse']['matcher'])){ if(in_array($settings['sparse']['matcher'],['sequential','exhaustive'],true)){$out['sparse']['matcher']=$settings['sparse']['matcher'];} else {$errors['sparse.matcher']='unsupported value';} }
    if(isset($settings['sparse']['loop_detection'])){$out['sparse']['loop_detection']=filter_var($settings['sparse']['loop_detection'],FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE)??false;}
    foreach(['preview','standard','fullhd'] as $mode){ foreach(['max_image_size'=>[320,3840,false],'num_src_images'=>[2,50,false],'chunk_overlap'=>[0,60,false],'target_images_per_chunk'=>[10,200,false],'max_images_per_chunk'=>[10,300,false],'mesh_depth'=>[5,12,false],'target_faces'=>[10000,2000000,false],'density_quantile'=>[0,0.30,true],'statistical_nb_neighbors'=>[4,100,false],'statistical_std_ratio'=>[0.1,10,true],'radius_nb_points'=>[1,50,false],'radius_multiplier'=>[0.5,20,true],'crop_low_percentile'=>[0,0.20,true],'crop_high_percentile'=>[0.80,1,true],'minimum_component_ratio'=>[0,1,true],'maximum_triangle_edge_multiplier'=>[1,100,true]] as $k=>$r){$num($mode.'.'.$k,$r[0],$r[1],$r[2]);} if(isset($settings[$mode]['mesh_engine'])){ if(in_array($settings[$mode]['mesh_engine'],['open3d','colmap'],true)){$out[$mode]['mesh_engine']=$settings[$mode]['mesh_engine'];} else {$errors[$mode.'.mesh_engine']='unsupported value';} } }
    $merged=array_replace_recursive($defaults,$out);
    foreach(['preview','standard','fullhd'] as $m){ if($merged[$m]['max_images_per_chunk'] < $merged[$m]['target_images_per_chunk']){$errors[$m.'.max_images_per_chunk']='must be >= target_images_per_chunk';} if($merged[$m]['chunk_overlap'] >= $merged[$m]['target_images_per_chunk']){$errors[$m.'.chunk_overlap']='must be < target_images_per_chunk';} if($merged[$m]['num_src_images'] >= $merged[$m]['max_images_per_chunk']){$errors[$m.'.num_src_images']='must be < max_images_per_chunk';} }
    if($errors){ throw new InvalidArgumentException('Invalid SfM settings: '.json_encode($errors,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); }
    return $out;
}

function sfm_quality_profiles(): array { return [
    'fast'=>['target_frames'=>240,'resolution_mode'=>'preview','max_image_size'=>640,'quality_filter'=>true],
    'balanced'=>['target_frames'=>400,'resolution_mode'=>'preview','max_image_size'=>640,'quality_filter'=>true],
    'detailed'=>['target_frames'=>550,'resolution_mode'=>'standard','max_image_size'=>1600,'quality_filter'=>true],
    'maximum'=>['target_frames'=>750,'resolution_mode'=>'fullhd','max_image_size'=>1920,'quality_filter'=>true],
]; }
function sfm_auto_sequential_overlap(int $selected,bool $loop=false): int { $v=$selected<120?15:($selected<250?20:($selected<450?30:($selected<700?40:50))); if($loop){$v=max(10,(int)floor($v*0.75));} return max(1,min($v,max(1,$selected-1))); }
function sfm_auto_dense_parameters(int $maxImageSize,int $registeredImages=0,?int $ramGb=null): array { if($maxImageSize<=640){$target=50;$max=80;} elseif($maxImageSize<=1600){$target=40;$max=60;} else {$target=30;$max=45;} if($ramGb!==null && $ramGb>0 && $ramGb<24){$target=max(20,(int)floor($target*0.75));$max=max($target,(int)floor($max*0.75));} $overlap=max(1,(int)round($target*0.30)); $src=$registeredImages<80?8:($registeredImages<160?12:($registeredImages<300?16:($registeredImages<500?20:24))); $src=min(30,$src,max(2,(int)floor($target/3))); return ['num_src_images'=>$src,'chunk_overlap'=>$overlap,'target_images_per_chunk'=>$target,'max_images_per_chunk'=>$max]; }

function sfm_mode_parameters(array $settings,string $mode): array { $m=$settings[$mode]??[]; return ['extract'=>$settings['extract']??[],'sparse'=>$settings['sparse']??[],'dense'=>['max_image_size'=>$m['max_image_size']??null,'num_src_images'=>$m['num_src_images']??null,'chunk_overlap'=>$m['chunk_overlap']??null,'target_images_per_chunk'=>$m['target_images_per_chunk']??null,'max_images_per_chunk'=>$m['max_images_per_chunk']??null],'mesh'=>['engine'=>$m['mesh_engine']??'open3d','depth'=>$m['mesh_depth']??null,'target_faces'=>$m['target_faces']??null,'density_quantile'=>$m['density_quantile']??null,'statistical_nb_neighbors'=>$m['statistical_nb_neighbors']??null,'statistical_std_ratio'=>$m['statistical_std_ratio']??null,'radius_nb_points'=>$m['radius_nb_points']??null,'radius_multiplier'=>$m['radius_multiplier']??null,'crop_low_percentile'=>$m['crop_low_percentile']??null,'crop_high_percentile'=>$m['crop_high_percentile']??null,'minimum_component_ratio'=>$m['minimum_component_ratio']??null,'maximum_triangle_edge_multiplier'=>$m['maximum_triangle_edge_multiplier']??null]]; }