<?php
declare(strict_types=1);
$root=sys_get_temp_dir().'/apw_'.bin2hex(random_bytes(4));define('APP_STORAGE_DIR',$root);mkdir($root.'/orders/o/sessions/s/capture_bundles',0775,true);putenv('AUTO_PHOTO_BUNDLE_TEST_MODE=true');
require_once __DIR__.'/../libs/auto_photo_prepare_web_lib.php';
function apw(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
function apw_o(int $n,int $l):string{return str_pad(decoct($n),$l-1,'0',STR_PAD_LEFT)."\0";}
function apw_h(string $n,int $z):string{$h=str_pad($n,100,"\0").apw_o(0644,8).apw_o(0,8).apw_o(0,8).apw_o($z,12).apw_o(0,12).str_repeat(' ',8).'0'.str_repeat("\0",100)."ustar\0".'00'.str_repeat("\0",32+32+8+8+155+12);$sum=array_sum(array_map('ord',str_split($h)));return substr_replace($h,str_pad(decoct($sum),6,'0',STR_PAD_LEFT)."\0 ",148,8);}
function apw_tgz(string $p):void{$jpg="\xFF\xD8\xFF\xC0\x00\x11\x08\x0C\x00\x10\x00\x03\x01\x11\x00\x02\x11\x00\x03\x11\x00".str_repeat("A",64)."\xFF\xD9";$photos=['photos/frame_000001.jpg','photos/frame_000002.jpg'];$meta=[];foreach($photos as $i=>$f)$meta[]=json_encode(['sequence'=>$i+1,'file'=>$f,'photo_uuid'=>'p'.$i,'image_width'=>4096,'image_height'=>3072]);$m=[['bundle_manifest.json',json_encode(['bundle_schema_version'=>1,'bundle_type'=>'maklertour_capture_bundle','capture_type'=>'auto_photo_session','app_bundle_uuid'=>'u','photos_count'=>2])],['capture/manifest.json',json_encode(['schema_version'=>1,'capture_type'=>'auto_photo_session','capture_uuid'=>'u','photos_count'=>2,'photos'=>$photos])],['capture/camera_info.json','{"camera_id":"0"}'],['capture/photos/frame_000001.jpg',$jpg],['capture/photos/frame_000002.jpg',$jpg],['capture/photos_metadata.jsonl',implode("\n",$meta)."\n"],['capture/imu.jsonl',implode("\n",$meta)."\n"],['capture/quality.jsonl',"{}\n"],['capture/events.jsonl',"{}\n"]];$tar='';foreach($m as [$n,$b])$tar.=apw_h($n,strlen($b)).$b.str_repeat("\0",(512-strlen($b)%512)%512);file_put_contents($p,gzencode($tar.str_repeat("\0",1024)));}
class APWR extends mysqli_result{public function __construct(private array $rows){}public function fetch_assoc():array|null|false{return array_shift($this->rows)??null;}}
class APWS extends mysqli_stmt{public array $args=[];public function __construct(private APWD $db,private string $sql){}public function bind_param(string $types,mixed &...$vars):bool{$this->args=$vars;return true;}public function execute(?array $params=null):bool{return true;}public function get_result():mysqli_result|false{return new APWR($this->db->rows($this->sql,$this->args));}public function close():true{return true;}}
class APWD extends mysqli{public int|string $insert_id=99;public int $inserts=0,$commits=0,$rollbacks=0;public function __construct(public array $bundle){}public function begin_transaction(int $flags=0,?string $name=null):bool{return true;}public function commit(int $flags=0,?string $name=null):bool{$this->commits++;return true;}public function rollback(int $flags=0,?string $name=null):bool{$this->rollbacks++;return true;}public function prepare(string $sql):mysqli_stmt|false{return new APWS($this,$sql);}public function rows(string $sql,array $a):array{if(str_contains($sql,'capture_bundles'))return [$this->bundle];if(str_contains($sql,'remote_job_id=?'))return [];if(str_contains($sql,'JSON_VALID'))return [];return [];} }
$archive=$root.'/orders/o/sessions/s/capture_bundles/b.tgz';apw_tgz($archive);$row=['id'=>8,'order_id'=>31,'capture_session_id'=>65,'app_bundle_uuid'=>'u','capture_type'=>'auto_photo_session','filename'=>'b.tgz','storage_path'=>'orders/o/sessions/s/capture_bundles/b.tgz','size_bytes'=>filesize($archive),'status'=>'UPLOADED','created_at'=>null,'updated_at'=>null];$db=new APWD($row);$hash=hash_file('sha256',$archive);$result=auto_photo_prepare_web_start_bundle($db,31,'8',static fn()=>99,static fn()=>12345);$base=dirname(auto_photo_bundle_index_cache_path($row,$archive));apw($result['duplicate']===false&&$result['input_images']===2,'real start bundle');apw(is_file($base.'/index.json')&&is_file($base.'/materialization.json'),'index materialization');apw(hash_file('sha256',$archive)===$hash&&$db->commits===1&&$db->rollbacks===0,'immutable commit');foreach([0,'0','01',-1,1.2,[],null,' 8']as$x)try{auto_photo_prepare_web_bundle_id($x);throw new RuntimeException('bad id');}catch(InvalidArgumentException){}echo "OK\n";
