<?php
declare(strict_types=1);
require_once __DIR__ . '/../libs/auto_photo_sparse_ui_render_lib.php';
function apsa_check(bool $condition, string $name): void { if (!$condition) { throw new RuntimeException($name); } }
$model = ['model_id'=>0,'registered_images'=>118,'registered_percent'=>66.3,'points3D_count'=>23230,'first_image'=>'first','last_image'=>'last','frame_ranges_label'=>'range','shared_images_label'=>'shared','selected'=>false,'recommended'=>false,'can_select'=>true,'can_export'=>true,'export'=>['status'=>'DONE','progress_percent'=>100,'db_job_id'=>900,'message'=>'export','download_url'=>'/api/file?x=1&y=2']];
$dto = ['visible'=>true,'bundle'=>['id'=>7,'capture_session_id'=>63,'photos_count'=>178,'status'=>'UPLOADED','app_bundle_uuid'=>'UUID'],'prepare'=>null,'active_jobs'=>false,'runs'=>[['sparse_db_job_id'=>746,'sparse_remote_job_id'=>9002,'status'=>'DONE','progress_percent'=>100,'matcher'=>'sequential','retry_mode'=>'','models_count'=>1,'input_images'=>178,'message'=>'run','recommended_run'=>false,'merge_warning'=>false,'can_retry_exhaustive'=>true,'models'=>[$model]]]];
$context = ['post_url'=>'/order.php?id=30','csrf_name'=>'secCode','csrf_value'=>'csrf-test-token'];
$beforeDto=serialize($dto); $beforeContext=serialize($context); $noContext=auto_photo_sparse_ui_render($dto); apsa_check(str_contains($noContext['pane'],'Скачать PLY')&&!str_contains($noContext['pane'],'<form')&&!str_contains($noContext['pane'],'auto_photo_sparse_'),'no context read only');
foreach (['post_url','csrf_name','csrf_value'] as $key) { $incomplete=$context; $incomplete[$key]=''; apsa_check(!str_contains(auto_photo_sparse_ui_render($dto,$incomplete)['pane'],'<form'),'incomplete '.$key); }
$pane=auto_photo_sparse_ui_render($dto,$context)['pane'];
foreach (['method="post"','action="/order.php?id=30"','name="secCode"','value="csrf-test-token"','auto_photo_sparse_select_model','auto_photo_sparse_retry_exhaustive','auto_photo_sparse_export_ply','name="sparse_db_job_id" value="746"','name="model_id" value="0"','Выбрать модель','Повторить с exhaustive matcher','Экспортировать PLY','Создать отдельный exhaustive sparse retry? Исходный sparse job изменён не будет.'] as $needle) apsa_check(str_contains($pane,$needle),'action '.$needle);
apsa_check(substr_count($pane,'auto_photo_sparse_select_model')===1 && substr_count($pane,'auto_photo_sparse_retry_exhaustive')===1 && substr_count($pane,'auto_photo_sparse_export_ply')===1,'one of each action');
$denied=$dto; $denied['runs'][0]['can_retry_exhaustive']=false; $denied['runs'][0]['models'][0]['can_select']=false; $denied['runs'][0]['models'][0]['can_export']=false; $deniedPane=auto_photo_sparse_ui_render($denied,$context)['pane']; apsa_check(!str_contains($deniedPane,'<form')&&str_contains($deniedPane,'Скачать PLY'),'denied read only');
foreach (['sfm_export_ply_web','sfm_retry_job','sfm_colmap_dense_web','sfm_reconstruction_preview_web','sfm_reconstruction_hq_web'] as $forbidden) apsa_check(!str_contains($pane,$forbidden),'no legacy '.$forbidden);
foreach (['output_path','input_path','log_path','remote_job_id','parent_remote_job_id','capture_session_id','capture_bundle_id','app_bundle_uuid','matcher','retry_mode','pipeline_run_id'] as $name) apsa_check(!str_contains($pane,'name="'.$name.'"'),'no client field '.$name);
$evil=['post_url'=>'\"><script>alert(1)</script>','csrf_name'=>'\"><script>alert(1)</script>','csrf_value'=>'\"><script>alert(1)</script>']; $evilPane=auto_photo_sparse_ui_render($dto,$evil)['pane']; apsa_check(str_contains($evilPane,'<form')&&!str_contains($evilPane,'<script>')&&str_contains($evilPane,'&lt;script&gt;'),'context escaping');
apsa_check(serialize($dto)===$beforeDto&&serialize($context)===$beforeContext,'immutable');
$simple=(string)file_get_contents(__DIR__.'/../www/order_simple.php'); foreach(['$autoPhotoSparseUiActionContext','\'post_url\' => \'/order.php?id=\' . $orderId',"'csrf_name' => 'secCode'","\$_SESSION['secCode']",'auto_photo_sparse_ui_render($autoPhotoSparseUi,$autoPhotoSparseUiActionContext)'] as $needle) apsa_check(str_contains($simple,$needle),'simple '.$needle); apsa_check(!str_contains($simple,'random_bytes'),'simple no token generation');
$route=(string)file_get_contents(__DIR__.'/../www/order.php'); foreach(["\$_SESSION['secCode']","\$_POST['secCode']",'hash_equals','invalid_csrf'] as $needle) apsa_check(str_contains($route,$needle),'csrf helper '.$needle);
$routes=[['auto_photo_sparse_select_model','auto_photo_sparse_web_select_model','photo_model_selected=1'],['auto_photo_sparse_retry_exhaustive','auto_photo_sparse_web_enqueue_exhaustive','photo_retry_queued=1'],['auto_photo_sparse_export_ply','auto_photo_sparse_web_enqueue_export','photo_export_queued=1']]; foreach($routes as [$action,$service,$flag]) { $start=strpos($route,"\$action === '$action'"); $end=strpos($route,"\n if(",$start+1); $fragment=substr($route,$start,$end-$start); foreach(['$canDeleteMedia','order_auto_photo_sparse_require_csrf',$service,$flag,'#simple-photo-sfm'] as $needle) apsa_check(str_contains($fragment,$needle),$action.' '.$needle); apsa_check(strpos($fragment,'order_auto_photo_sparse_require_csrf')<strpos($fragment,$service),$action.' csrf first'); foreach(['SELECT','INSERT','UPDATE','DELETE','FOR UPDATE','begin_transaction','commit','rollback'] as $forbidden) apsa_check(!str_contains($fragment,$forbidden),$action.' no sql'); }
foreach(['photo_model_selected=1#simple-photo-sfm','photo_retry_queued=1#simple-photo-sfm','photo_export_queued=1#simple-photo-sfm','photo_export_exists=1#simple-photo-sfm'] as $redirect) apsa_check(str_contains($route,$redirect),'redirect '.$redirect);
$exportStart=strpos($route,"\$action === 'auto_photo_sparse_export_ply'"); $exportEnd=strpos($route,"\n if(",$exportStart+1); apsa_check(!str_contains(substr($route,$exportStart,$exportEnd-$exportStart),'sfm_export_ply_web'),'separate legacy export');
$template=(string)file_get_contents(__DIR__.'/../templates/maklertour_order_simple.html'); foreach(["window.addEventListener('load'","window.location.hash !== '#simple-photo-sfm'",'simple-photo-sfm-tab','window.bootstrap.Tab','getOrCreateInstance','.show()'] as $needle) apsa_check(str_contains($template,$needle),'template activation '.$needle); foreach(["classList.add('active')","classList.add('show')"] as $forbidden) apsa_check(!str_contains($template,$forbidden),'template no manual '.$forbidden); apsa_check(strpos($template,"window.location.hash !== '#simple-photo-sfm'")<strpos($template,'getOrCreateInstance'),'template exact hash first');
echo "OK\n";
