<?php
declare(strict_types=1);
$root=sys_get_temp_dir().'/auto_photo_sparse_ui_web_'.bin2hex(random_bytes(6)); define('AUTO_PHOTO_SPARSE_OUTPUT_ROOT',$root); define('APP_STORAGE_DIR',$root.'/storage'); mkdir(APP_STORAGE_DIR.'/orders',0775,true);
require_once __DIR__.'/../libs/auto_photo_sparse_ui_web_lib.php';
function t(bool $ok,string $name):void { if(!$ok)throw new RuntimeException($name); }
function j(array $a):string{return (string)json_encode($a,JSON_THROW_ON_ERROR);}
function b(int $id=7,int $sid=63):array{return ['id'=>$id,'order_id'=>30,'capture_session_id'=>$sid,'app_bundle_uuid'=>'b'.$id,'capture_type'=>'auto_photo_session','status'=>'UPLOADED'];}
function p(int $id=745,int $remote=9001,int $bundle=7,int $sid=63,string $status='DONE',array|string|null $params=null):array{$params??=['source_type'=>'auto_photo_bundle','pipeline_mode'=>'prepare','capture_bundle_id'=>$bundle,'app_bundle_uuid'=>'b'.$bundle,'input_images'=>178];return ['id'=>$id,'order_id'=>30,'capture_session_id'=>$sid,'job_type'=>AUTO_PHOTO_PREPARE_JOB_TYPE,'remote_job_id'=>$remote,'status'=>$status,'progress_percent'=>50,'message'=>'prepare','parameters_json'=>is_array($params)?j($params):$params];}
function s(int $id=746,int $remote=434136404,int $parent=9001,int $bundle=7,int $sid=63,array|string|null $params=null):array{$params??=['source_type'=>'auto_photo_prepare','standalone_sparse'=>true,'prepare_job_id'=>745,'prepare_remote_job_id'=>9001,'capture_bundle_id'=>$bundle,'app_bundle_uuid'=>'b'.$bundle,'input_images'=>178];return ['id'=>$id,'order_id'=>30,'capture_session_id'=>$sid,'job_type'=>'COLMAP_SPARSE','remote_job_id'=>$remote,'parent_remote_job_id'=>$parent,'status'=>'DONE','progress_percent'=>100,'message'=>'sparse','parameters_json'=>is_array($params)?j($params):$params,'pipeline_run_id'=>null];}
function e(int $id=900,int $remote=9100,int $parent=434136404,string $status='DONE',array|string|null $params=null,string|null $output=null):array{$params??=['source_type'=>'auto_photo_sparse','standalone_photo_export'=>true,'sparse_job_id'=>434136404,'model_id'=>0];return ['id'=>$id,'order_id'=>30,'capture_session_id'=>63,'job_type'=>'EXPORT_PLY','remote_job_id'=>$remote,'parent_remote_job_id'=>$parent,'output_path'=>$output??auto_photo_sparse_output_path($remote).'/sparse_0.ply','status'=>$status,'progress_percent'=>0,'message'=>'export','parameters_json'=>is_array($params)?j($params):$params];}
try {
 $cacheArchive=APP_STORAGE_DIR.'/orders/o/sessions/s/capture_bundles/bundle.tgz';mkdir(dirname($cacheArchive),0775,true);file_put_contents($cacheArchive,'sentinel');$cacheRow=['id'=>8,'order_id'=>30,'capture_session_id'=>63,'app_bundle_uuid'=>'b8','capture_type'=>AUTO_PHOTO_BUNDLE_CAPTURE_TYPE,'filename'=>'bundle.tgz','storage_path'=>'orders/o/sessions/s/capture_bundles/bundle.tgz','size_bytes'=>8,'status'=>'UPLOADED'];$cachePath=auto_photo_bundle_index_cache_path($cacheRow,$cacheArchive);mkdir(dirname($cachePath),0775,true);file_put_contents($cachePath,j(['schema_version'=>AUTO_PHOTO_BUNDLE_INDEX_SCHEMA_VERSION,'capture_bundle_id'=>8,'order_id'=>30,'capture_session_id'=>63,'app_bundle_uuid'=>'b8','capture_type'=>AUTO_PHOTO_BUNDLE_CAPTURE_TYPE,'validation_status'=>'VALID','blocking_errors'=>[],'photos_count_actual'=>87,'photos'=>array_fill(0,87,[])]));$summary=auto_photo_sparse_ui_web_bundle_index_summary($cacheRow);t($summary===['photos_count'=>87],'cached index 87');$cacheDto=auto_photo_sparse_ui_web_bundle($cacheRow,30);t($cacheDto['photos_count']===87&&$cacheDto['photos_count_known']===true,'cached known');file_put_contents($cachePath,'{');t(auto_photo_sparse_ui_web_bundle_index_summary($cacheRow)===null,'cached malformed');
 $models=['models'=>[['model_id'=>0,'registered_images'=>118,'points3D_count'=>23230]]];
 $only=auto_photo_sparse_ui_web_build_from_rows(30,false,[b()],[],[],[],null);t($only['visible']&&$only['prepare']===null&&$only['runs']===[]&&$only['bundle']['id']===7,'bundle only');
 $running=auto_photo_sparse_ui_web_build_from_rows(30,true,[b()],[],[p(status:'RUNNING')],[],null);t($running['visible']&&$running['prepare']['status']==='RUNNING'&&$running['active_jobs']&&$running['runs']===[]&&$running['bundle']['photos_count']===178,'prepare running');
 $error=auto_photo_sparse_ui_web_build_from_rows(30,true,[b()],[],[p(status:'ERROR')],[],null);t($error['visible']&&$error['prepare']['status']==='ERROR'&&!$error['active_jobs'],'prepare error');
 $bundles=[b(),b(8,64)];$bad=s(800,434136405,9002,8,64,['source_type'=>'auto_photo_prepare','standalone_sparse'=>true,'prepare_job_id'=>999,'prepare_remote_job_id'=>9002,'capture_bundle_id'=>8,'app_bundle_uuid'=>'b8','input_images'=>3]);$good=s();$prepares=[p(),p(750,9002,8,64)];
 foreach([[$bundles,[$bad,$good]], [array_reverse($bundles),array_reverse([$bad,$good])]] as [$bs,$ss])t(auto_photo_sparse_ui_web_select_bundle($bs,$ss,$prepares,30)['id']===7,'sparse chain fallback');
 $prepares=[p(745,9001,7),p(750,9002,8,64)];foreach([[$bundles,[]],[array_reverse($bundles),[]]] as [$bs,$ss])t(auto_photo_sparse_ui_web_select_bundle($bs,$ss,$prepares,30)['id']===8,'prepare fallback');
 foreach([[$bundles,[]],[array_reverse($bundles),[]]] as [$bs,$ss])t(auto_photo_sparse_ui_web_select_bundle($bs,$ss,[],30)['id']===8,'bundle id fallback');
 foreach([p(params:'{'),p(params:['source_type'=>'wrong','pipeline_mode'=>'prepare','capture_bundle_id'=>7,'app_bundle_uuid'=>'b7']),p(params:['source_type'=>'auto_photo_bundle','pipeline_mode'=>'wrong','capture_bundle_id'=>7,'app_bundle_uuid'=>'b7']),p(params:['source_type'=>'auto_photo_bundle','pipeline_mode'=>'prepare','capture_bundle_id'=>8,'app_bundle_uuid'=>'b7']),p(params:['source_type'=>'auto_photo_bundle','pipeline_mode'=>'prepare','capture_bundle_id'=>7,'app_bundle_uuid'=>'wrong']),array_merge(p(),['order_id'=>31]),array_merge(p(),['capture_session_id'=>99]),array_merge(p(),['id'=>0]),array_merge(p(),['remote_job_id'=>0])] as $badPrepare)t(auto_photo_sparse_ui_web_prepare_for_bundle($badPrepare,30,b())===null,'prepare markers');
 $prepareNoImages=p(params:['source_type'=>'auto_photo_bundle','pipeline_mode'=>'prepare','capture_bundle_id'=>7,'app_bundle_uuid'=>'b7']);$prepareZero=p(params:['source_type'=>'auto_photo_bundle','pipeline_mode'=>'prepare','capture_bundle_id'=>7,'app_bundle_uuid'=>'b7','input_images'=>0]);$prepareTwoHundred=p(params:['source_type'=>'auto_photo_bundle','pipeline_mode'=>'prepare','capture_bundle_id'=>7,'app_bundle_uuid'=>'b7','input_images'=>200]);foreach([[$prepareNoImages,178],[$prepareZero,178],[$prepareTwoHundred,200]] as [$prepare,$expected])t(auto_photo_sparse_ui_web_build_from_rows(30,true,[b()],[s()],[$prepare],[],static fn(int $id):array=>$models)['bundle']['photos_count']===$expected,'photos fallback');
 $exportPath=auto_photo_sparse_output_path(9100).'/sparse_0.ply';mkdir(dirname($exportPath),0775,true);file_put_contents($exportPath,'ply');$dto=auto_photo_sparse_ui_web_build_from_rows(30,false,[b()],[s()],[p()],[434136404=>[e()]],static fn(int $id):array=>$models);t($dto['visible']&&$dto['prepare']['db_job_id']===745&&$dto['runs'][0]['sparse_remote_job_id']===434136404&&$dto['runs'][0]['models'][0]['model_id']===0&&$dto['runs'][0]['models'][0]['export']['db_job_id']===900&&$dto['runs'][0]['models'][0]['export']['download_url']!==''&&!$dto['runs'][0]['models'][0]['can_export'],'746/model 0/ready export/canManage');
 foreach([s(params:'{'),s(params:['source_type'=>'auto_photo_prepare','standalone_sparse'=>false,'prepare_job_id'=>745,'prepare_remote_job_id'=>9001,'capture_bundle_id'=>7,'app_bundle_uuid'=>'b7']),array_merge(s(),['pipeline_run_id'=>1]),array_merge(s(),['capture_session_id'=>99])] as $badSparse)t(auto_photo_sparse_ui_web_sparse($badSparse,30,b())===null,'sparse filters');
 $chainParams=['source_type'=>'auto_photo_prepare','standalone_sparse'=>true,'prepare_job_id'=>745,'prepare_remote_job_id'=>9001,'capture_bundle_id'=>7,'app_bundle_uuid'=>'b7','input_images'=>178];foreach(['prepare_job_id'=>null,'prepare_remote_job_id'=>null] as $key=>$value){$x=$chainParams;unset($x[$key]);t(!auto_photo_sparse_ui_web_sparse_prepare(s(params:$x),p()),'missing prepare id');}foreach([['prepare_job_id'=>0],['prepare_remote_job_id'=>0],['prepare_job_id'=>'01'],['prepare_remote_job_id'=>'01'],['prepare_job_id'=>744],['prepare_remote_job_id'=>9002],['prepare_job_id'=>744,'prepare_remote_job_id'=>9002]] as $change){$x=array_replace($chainParams,$change);t(!auto_photo_sparse_ui_web_sparse_prepare(s(params:$x),p()),'invalid prepare chain parameters');}$wrongParent=s(parent:9002,params:$chainParams);t(!auto_photo_sparse_ui_web_sparse_prepare($wrongParent,p()),'wrong sparse parent');
 t(auto_photo_sparse_ui_web_export(e(params:['source_type'=>'video_sparse']),30,s())===null&&auto_photo_sparse_ui_web_export(e(parent:12),30,s())===null&&auto_photo_sparse_ui_web_export(array_merge(e(),['id'=>0]),30,s())===null&&auto_photo_sparse_ui_web_export(array_merge(e(),['remote_job_id'=>0]),30,s())===null&&auto_photo_sparse_ui_web_export(e(remote:434136404),30,s())===null&&auto_photo_sparse_ui_web_export(e(output:'/wrong/path'),30,s())===null,'export filters, separate id and output path');
 $missing=e(remote:9101);t(auto_photo_sparse_ui_web_export($missing,30,s())===null,'missing DONE output');$empty=e(remote:9102);mkdir(dirname($empty['output_path']),0775,true);file_put_contents($empty['output_path'],'');t(auto_photo_sparse_ui_web_export($empty,30,s())===null,'empty DONE output');$linked=e(remote:9103);mkdir(dirname($linked['output_path']),0775,true);symlink($exportPath,$linked['output_path']);t(auto_photo_sparse_ui_web_export($linked,30,s())===null,'symlink DONE output');
 $active=e(status:'RUNNING',params:['source_type'=>'auto_photo_sparse','standalone_photo_export'=>true,'sparse_job_id'=>434136404,'model_id'=>'01']);$activeDto=auto_photo_sparse_ui_web_build_from_rows(30,true,[b()],[s()],[p()],[434136404=>[$active]],static fn(int $id):array=>$models);t($activeDto['active_jobs']&&$activeDto['runs'][0]['models'][0]['export']===null,'active malformed export');
 $dir=auto_photo_sparse_output_path(434136404);mkdir($dir.'/colmap',0775,true);$file=$dir.'/colmap/sparse_components.json';file_put_contents($file,j($models));t(auto_photo_sparse_ui_web_components(434136404)['models'][0]['model_id']===0,'valid manifest');t(auto_photo_sparse_ui_web_components(1)===['models'=>[]],'missing manifest');file_put_contents($file,'{');t(auto_photo_sparse_ui_web_components(434136404)===['models'=>[]],'invalid manifest');file_put_contents($file,str_repeat('x',AUTO_PHOTO_SPARSE_UI_WEB_MANIFEST_MAX_BYTES+1));t(auto_photo_sparse_ui_web_components(434136404)===['models'=>[]],'oversized manifest');
 @unlink($file);symlink('/etc/passwd',$file);t(auto_photo_sparse_ui_web_components(434136404)===['models'=>[]],'manifest symlink');@unlink($file);@rmdir($dir.'/colmap');@rmdir($dir);$outside=$root.'_outside';mkdir($outside);symlink($outside,$dir);t(auto_photo_sparse_ui_web_components(434136404)===['models'=>[]],'job symlink');@unlink($dir);mkdir($dir);symlink($outside,$dir.'/colmap');t(auto_photo_sparse_ui_web_components(434136404)===['models'=>[]],'colmap symlink');
 $source=(string)file_get_contents(__DIR__.'/../libs/auto_photo_sparse_ui_web_lib.php');t(preg_match('/\b(INSERT|UPDATE|DELETE|REPLACE|FOR[[:space:]]+UPDATE|LOCK[[:space:]]+TABLES)\b/i',$source)!==1,'no modifying SQL');t(array_keys($dto)===['visible','bundle','prepare','runs','recommended_sparse_db_job_id','active_jobs'],'DTO shape');echo "OK\n";
} finally {$rm=static function(string $path)use(&$rm):void{if(is_link($path)||is_file($path)){@unlink($path);return;}if(!is_dir($path))return;foreach(scandir($path)?:[]as$n)if($n!=='.'&&$n!=='..')$rm($path.'/'.$n);@rmdir($path);};$rm($root);$rm($root.'_outside');}
