<?php

declare(strict_types=1);

$storageRoot = sys_get_temp_dir() . '/apbm_storage_' . bin2hex(random_bytes(4));
mkdir($storageRoot . '/orders', 0775, true);
define('APP_STORAGE_DIR', $storageRoot);
putenv('AUTO_PHOTO_BUNDLE_TEST_MODE=true');
require_once __DIR__ . '/../libs/auto_photo_bundle_materialize_lib.php';

$failures = 0;
function mtassert(bool $ok, string $msg): void { global $failures; if (!$ok) { $failures++; echo "FAIL: $msg\n"; } }
function mjpg(int $w = 16, int $h = 12, string $tail = "\xFF\xD9"): string { return "\xFF\xD8\xFF\xC0\x00\x11\x08" . chr(($h>>8)&255) . chr($h&255) . chr(($w>>8)&255) . chr($w&255) . "\x03\x01\x11\x00\x02\x11\x00\x03\x11\x00" . str_repeat('A', 32) . $tail; }
function mtar_octal(int $n, int $len): string { return str_pad(decoct($n), $len - 1, '0', STR_PAD_LEFT) . "\0"; }
function mtar_header(string $name, int $size, string $type = '0', bool $badChecksum = false, ?string $rawSize = null): string { $h = str_pad(substr($name,0,100),100,"\0") . mtar_octal(0644,8) . mtar_octal(0,8) . mtar_octal(0,8) . ($rawSize ?? mtar_octal($size,12)) . mtar_octal(0,12) . str_repeat(' ',8) . $type . str_repeat("\0",100) . "ustar\0" . "00" . str_repeat("\0",32) . str_repeat("\0",32) . str_repeat("\0",8) . str_repeat("\0",8) . str_repeat("\0",155) . str_repeat("\0",12); $sum=0; for($i=0;$i<512;$i++) $sum += ord($h[$i]); if($badChecksum) $sum++; return substr_replace($h, str_pad(decoct($sum),6,'0',STR_PAD_LEFT) . "\0 ",148,8); }
function mtgz(array $jpgs = [], array $extra = [], array $opts = []): string { $jpgs = $jpgs ?: ['capture/photos/frame_000001.jpg'=>mjpg(), 'capture/photos/frame_000002.jpg'=>mjpg(20,10)]; $photos = array_map(fn($p)=>'photos/'.basename($p), array_keys($jpgs)); $members = [['bundle_manifest.json', json_encode(['bundle_schema_version'=>1,'bundle_type'=>'maklertour_capture_bundle','capture_type'=>'auto_photo_session','app_bundle_uuid'=>'uuid-1','photos_count'=>count($jpgs)]),'0',false,null], ['capture/manifest.json', json_encode(['schema_version'=>1,'capture_type'=>'auto_photo_session','capture_uuid'=>'uuid-1','photos_count'=>count($jpgs),'photos'=>$photos]),'0',false,null], ['capture/camera_info.json', json_encode(['camera_id'=>'0']),'0',false,null]]; $seq=1; $meta=[]; foreach(array_keys($jpgs) as $n) { $sof=auto_photo_bundle_parse_jpeg_sof($jpgs[$n]); $meta[]=['sequence'=>$seq++,'file'=>'photos/'.basename($n),'image_width'=>$sof['width']??16,'image_height'=>$sof['height']??12]; } $metaText=implode('\n', array_map('json_encode',$meta)) . '\n'; $members[]=['capture/photos_metadata.jsonl',$metaText,'0',false,null]; $members[]=['capture/imu.jsonl',$metaText,'0',false,null]; $members[]=['capture/quality.jsonl',json_encode(['ok'=>1]).'\n','0',false,null]; $members[]=['capture/events.jsonl',json_encode(['ok'=>1]).'\n','0',false,null]; foreach($jpgs as $n=>$c) $members[] = [$n,$c,'0',false,null]; foreach($extra as $m) $members[]=$m; $tar=''; foreach($members as $m) { [$n,$body,$type,$bad,$rawSize] = [$m[0],$m[1]??'',$m[2]??'0',$m[3]??false,$m[4]??null]; $declared = $rawSize === null ? strlen($body) : (is_int($rawSize) ? $rawSize : strlen($body)); $tar .= mtar_header($n,$declared,$type,$bad,is_string($rawSize)?$rawSize:null) . $body . str_repeat("\0", (512 - ($declared % 512)) % 512); } if (!($opts['no_end']??false)) $tar .= str_repeat("\0",1024); $dir=sys_get_temp_dir().'/apbm_'.bin2hex(random_bytes(4)); mkdir($dir); $tgz="$dir/bundle.tgz"; file_put_contents($tgz,gzencode($tar)); return $tgz; }
function mtgz_large_stream(int $count, int $jpegSize): string { $dir=sys_get_temp_dir().'/apbm_large_'.bin2hex(random_bytes(4)); mkdir($dir); $tgz="$dir/bundle.tgz"; $gz=gzopen($tgz,'wb9'); $photos=[]; for($i=1;$i<=$count;$i++) $photos[]=sprintf('photos/frame_%06d.jpg',$i); $bundle=json_encode(['bundle_schema_version'=>1,'bundle_type'=>'maklertour_capture_bundle','capture_type'=>'auto_photo_session','app_bundle_uuid'=>'uuid-1','photos_count'=>$count]); $man=json_encode(['schema_version'=>1,'capture_type'=>'auto_photo_session','capture_uuid'=>'uuid-1','photos_count'=>$count,'photos'=>$photos]); foreach([['bundle_manifest.json',$bundle],['capture/manifest.json',$man],['capture/camera_info.json',json_encode(['camera_id'=>'0'])]] as $m){ gzwrite($gz, mtar_header($m[0], strlen($m[1]))); gzwrite($gz,$m[1]); gzwrite($gz,str_repeat("\0",(512-(strlen($m[1])%512))%512)); } $meta=[]; for($i=1;$i<=$count;$i++) $meta[]=json_encode(['sequence'=>$i,'file'=>sprintf('photos/frame_%06d.jpg',$i),'image_width'=>16,'image_height'=>12]); $metaText=implode("\n",$meta)."\n"; foreach([['capture/photos_metadata.jsonl',$metaText],['capture/imu.jsonl',$metaText],['capture/quality.jsonl',"{}\n"],['capture/events.jsonl',"{}\n"]] as $m){ gzwrite($gz, mtar_header($m[0], strlen($m[1]))); gzwrite($gz,$m[1]); gzwrite($gz,str_repeat("\0",(512-(strlen($m[1])%512))%512)); } $prefix=substr(mjpg(),0,-2); $chunk=str_repeat('B',8192); for($i=1;$i<=$count;$i++){ $name=sprintf('capture/photos/frame_%06d.jpg',$i); gzwrite($gz, mtar_header($name,$jpegSize)); gzwrite($gz,$prefix); $left=$jpegSize-strlen($prefix)-2; while($left>0){$n=min($left,8192); gzwrite($gz,substr($chunk,0,$n)); $left-=$n;} gzwrite($gz,"\xFF\xD9"); gzwrite($gz,str_repeat("\0",(512-($jpegSize%512))%512)); } gzwrite($gz,str_repeat("\0",1024)); gzclose($gz); return $tgz; }
function mrow(string $rel): array { return ['id'=>7,'order_id'=>30,'capture_session_id'=>63,'app_bundle_uuid'=>'uuid-1','capture_type'=>'auto_photo_session','filename'=>basename($rel),'storage_path'=>$rel,'size_bytes'=>filesize(APP_STORAGE_DIR.'/'.$rel),'status'=>'UPLOADED']; }
function minst(string $tgz, ?array &$idx = null): array { static $n=0; $n++; $rel="orders/o$n/sessions/s$n/capture_bundles/bundle.tgz"; @mkdir(dirname(APP_STORAGE_DIR.'/'.$rel),0775,true); copy($tgz, APP_STORAGE_DIR.'/'.$rel); $row=mrow($rel); $idx=auto_photo_bundle_build_index_from_row($row); $idx['validation_status']='VALID'; $idx['blocking_errors']=[]; $idx['warnings']=[]; $base=auto_photo_bundle_materialization_base_dir($row, APP_STORAGE_DIR.'/'.$rel); @mkdir($base,0775,true); auto_photo_bundle_write_index_atomic($idx, $base.'/index.json'); return [$row,$base,APP_STORAGE_DIR.'/'.$rel]; }
function merr(callable $fn, string $code, string $msg): void { try { $fn(); mtassert(false,$msg); } catch (Throwable $e) { mtassert(str_contains($e->getMessage(), $code), $msg . ' got=' . $e->getMessage()); } }

[$row,$base,$archive] = minst(mtgz(), $idx); $r = auto_photo_bundle_materialize_from_row($row); mtassert($r['status']==='READY' && !($r['idempotent']??false) && is_dir($base.'/photos') && is_file($base.'/materialization.json'), 'valid materialization'); mtassert(auto_photo_bundle_materialize_from_row($row)['idempotent']===true, 'matching existing state'); file_put_contents($base.'/photos/extra.txt','x'); merr(fn()=>auto_photo_bundle_materialize_from_row($row),'existing_materialization_mismatch','extra file in existing photos'); unlink($base.'/photos/extra.txt'); file_put_contents($base.'/photos/frame_000001.jpg','bad'); merr(fn()=>auto_photo_bundle_materialize_from_row($row),'existing_materialization_mismatch','mismatching existing state');
[$drow,$dbase] = minst(mtgz(), $didx); $dr = auto_photo_bundle_materialize_from_row($drow, ['dry_run'=>true]); mtassert($dr['status']==='DRY_RUN' && ($dr['idempotent']??null)===false && !is_dir($dbase.'/photos') && !is_file($dbase.'/.materialize.lock'), 'full dry-run scan');
[$dmr,$dmb]=minst(mtgz(),$dmi); auto_photo_bundle_materialize_from_row($dmr,['index'=>$dmi]); unlink($dmb.'/.materialize.lock'); $beforeMatch=['mat'=>hash_file('sha256',$dmb.'/materialization.json'),'jpgs'=>array_map('hash_file',array_fill(0,count(glob($dmb.'/photos/*.jpg')),'sha256'),glob($dmb.'/photos/*.jpg'))]; $dryMatch=auto_photo_bundle_materialize_from_row($dmr,['index'=>$dmi,'dry_run'=>true]); mtassert($dryMatch['status']==='DRY_RUN' && ($dryMatch['idempotent']??null)===true && !is_file($dmb.'/.materialize.lock') && glob($dmb.'/.materialization.stage.*')===[] && hash_file('sha256',$dmb.'/materialization.json')===$beforeMatch['mat'] && array_map('hash_file',array_fill(0,count(glob($dmb.'/photos/*.jpg')),'sha256'),glob($dmb.'/photos/*.jpg'))===$beforeMatch['jpgs'], 'dry-run validates matching existing state without filesystem changes');
[$dxr,$dxb]=minst(mtgz(),$dxi); auto_photo_bundle_materialize_from_row($dxr,['index'=>$dxi]); unlink($dxb.'/.materialize.lock'); $dxm=json_decode(file_get_contents($dxb.'/materialization.json'),true); $dxm['total_bytes']++; file_put_contents($dxb.'/materialization.json',json_encode($dxm)); $beforeMismatch=['mat'=>hash_file('sha256',$dxb.'/materialization.json'),'jpgs'=>array_map('hash_file',array_fill(0,count(glob($dxb.'/photos/*.jpg')),'sha256'),glob($dxb.'/photos/*.jpg'))]; merr(fn()=>auto_photo_bundle_materialize_from_row($dxr,['index'=>$dxi,'dry_run'=>true]),'existing_materialization_mismatch','dry-run rejects mismatching existing state'); mtassert(is_file($dxb.'/materialization.json') && hash_file('sha256',$dxb.'/materialization.json')===$beforeMismatch['mat'] && array_map('hash_file',array_fill(0,count(glob($dxb.'/photos/*.jpg')),'sha256'),glob($dxb.'/photos/*.jpg'))===$beforeMismatch['jpgs'] && !is_file($dxb.'/.materialize.lock') && glob($dxb.'/.materialization.stage.*')===[], 'dry-run mismatch leaves existing state untouched');
[$jlr,$jlb]=minst(mtgz(),$jli); merr(fn()=>auto_photo_bundle_materialize_from_row($jlr,['index'=>$jli,'dry_run'=>true,'limits'=>['max_jpeg_count'=>1]]),'jpeg_count_limit_exceeded','JPEG count limit dry-run'); merr(fn()=>auto_photo_bundle_materialize_from_row($jlr,['index'=>$jli,'limits'=>['max_jpeg_count'=>1]]),'jpeg_count_limit_exceeded','JPEG count limit materialization'); mtassert(!is_dir($jlb.'/photos') && !is_file($jlb.'/materialization.json') && glob($jlb.'/.materialization.stage.*')===[], 'JPEG count limit cleans materialization artifacts');
[$jbr,$jbb]=minst(mtgz(),$jbi); $jbd=auto_photo_bundle_materialize_from_row($jbr,['index'=>$jbi,'dry_run'=>true,'limits'=>['max_jpeg_count'=>2]]); $jbm=auto_photo_bundle_materialize_from_row($jbr,['index'=>$jbi,'limits'=>['max_jpeg_count'=>2]]); mtassert($jbd['photos_count']===2 && $jbm['photos_count']===2, 'JPEG count limit boundary');
$cases = [];
[$r1,$b1,$a1]=minst(mtgz(), $i1); $i1['archive_sha256']='bad'; $cases[] = [$r1,$i1,'index_archive_sha256_mismatch','archive SHA mismatch'];
[$r2,$b2,$a2]=minst(mtgz(), $i2); $i2['capture_bundle_id']=999; $cases[] = [$r2,$i2,'index_capture_bundle_id_mismatch','index ID mismatch'];
[$r3,$b3,$a3]=minst(mtgz(), $i3); $i3['app_bundle_uuid']='other'; $cases[] = [$r3,$i3,'index_app_bundle_uuid_mismatch','index UUID mismatch'];
[$r4,$b4,$a4]=minst(mtgz(), $i4); $i4['validation_status']='WARNING'; $cases[] = [$r4,$i4,'index_not_valid','index status mismatch'];
foreach ($cases as [$rr,$ii,$code,$msg]) merr(fn()=>auto_photo_bundle_materialize_from_row($rr,['index'=>$ii,'dry_run'=>true]),$code,$msg);
[$mr,$mb]=minst(mtgz(['capture/photos/frame_000001.jpg'=>mjpg()]), $mi); $mi['photos'][]=['filename'=>'missing.jpg','archive_path'=>'capture/photos/missing.jpg','file_size_bytes'=>10,'width'=>1,'height'=>1]; $mi['photos_count_actual']=2; $mi['total_jpeg_bytes']+=10; merr(fn()=>auto_photo_bundle_materialize_from_row($mr,['index'=>$mi,'dry_run'=>true]),'missing_indexed_jpeg','missing indexed JPEG');
[$ur,$ub]=minst(mtgz(['capture/photos/frame_000001.jpg'=>mjpg()], [['capture/photos/extra.jpg',mjpg(),'0',false,null]]), $ui); $ui['photos']=array_slice($ui['photos'],0,1); $ui['photos_count_actual']=1; $ui['total_jpeg_bytes']=$ui['photos'][0]['file_size_bytes']; merr(fn()=>auto_photo_bundle_materialize_from_row($ur,['index'=>$ui,'dry_run'=>true]),'unexpected_jpeg','unexpected JPEG');
foreach ([['duplicate JPEG', mtgz([], [['capture/photos/frame_000001.jpg',mjpg(),'0',false,null]]), 'duplicate_member'], ['unsafe path', mtgz([], [['../evil.jpg','x','0',false,null]]), 'unsafe_archive_member'], ['special TAR types', mtgz([], [['capture/photos/link.jpg','', '2', false, null]]), 'unsupported_tar_type'], ['invalid tar size', (function(){ $h=mtar_header('capture/photos/bad.jpg',1,'0',false,str_repeat('Z',12)); $f=sys_get_temp_dir().'/apbm_badsize_'.bin2hex(random_bytes(4)).'.tgz'; file_put_contents($f,gzencode($h.'x'.str_repeat("\0",1024))); return $f; })(), 'invalid_tar_size']] as [$msg,$tgz,$code]) { [$tr,$tb]=minst($tgz,$ti); merr(fn()=>auto_photo_bundle_materialize_from_row($tr,['index'=>$ti,'dry_run'=>true]),$code,$msg); }
[$lr,$lb]=minst(mtgz(),$li); merr(fn()=>auto_photo_bundle_materialize_from_row($lr,['index'=>$li,'dry_run'=>true,'limits'=>['max_member_count'=>1]]),'member_count_limit_exceeded','member limit'); merr(fn()=>auto_photo_bundle_materialize_from_row($lr,['index'=>$li,'dry_run'=>true,'limits'=>['max_single_jpeg_bytes'=>1]]),'single_jpeg_limit_exceeded','JPEG limit');
$j=mjpg(); $tt=(function() use ($j){ $bundle=json_encode(['bundle_schema_version'=>1,'bundle_type'=>'maklertour_capture_bundle','capture_type'=>'auto_photo_session','app_bundle_uuid'=>'uuid-1','photos_count'=>1]); $man=json_encode(['schema_version'=>1,'capture_type'=>'auto_photo_session','capture_uuid'=>'uuid-1','photos_count'=>1,'photos'=>['photos/frame_000001.jpg']]); $tar=mtar_header('bundle_manifest.json',strlen($bundle)).$bundle.str_repeat("\0",(512-(strlen($bundle)%512))%512).mtar_header('capture/manifest.json',strlen($man)).$man.str_repeat("\0",(512-(strlen($man)%512))%512).mtar_header('capture/photos/frame_000001.jpg',strlen($j)+100).$j; $f=sys_get_temp_dir().'/apbm_trunc_'.bin2hex(random_bytes(4)).'.tgz'; file_put_contents($f,gzencode($tar)); return $f; })(); [$trow,$tb]=minst($tt,$ti); $ti['photos']=[['filename'=>'frame_000001.jpg','archive_path'=>'capture/photos/frame_000001.jpg','file_size_bytes'=>strlen($j)+100,'width'=>16,'height'=>12]]; $ti['photos_count_actual']=1; $ti['total_jpeg_bytes']=strlen($j)+100; merr(fn()=>auto_photo_bundle_materialize_from_row($trow,['index'=>$ti,'dry_run'=>true]),'truncated_member','truncated payload');
foreach ([['wrong file size', function($i){$i['photos'][0]['file_size_bytes']++; $i['total_jpeg_bytes']++; return $i;}, 'jpeg_size_mismatch'], ['wrong dimensions', function($i){$i['photos'][0]['width']++; return $i;}, 'jpeg_dimensions_mismatch']] as [$msg,$mut,$code]) { [$xr,$xb]=minst(mtgz(),$xi); $xi=$mut($xi); merr(fn()=>auto_photo_bundle_materialize_from_row($xr,['index'=>$xi,'dry_run'=>true]),$code,$msg); }
foreach ([['invalid SOI/SOF', ['capture/photos/frame_000001.jpg'=>'bad'], 'invalid_jpeg_soi'], ['missing EOI', ['capture/photos/frame_000001.jpg'=>mjpg(16,12,'XX')], 'missing_jpeg_eoi']] as [$msg,$jpgs,$code]) { [$jr,$jb]=minst(mtgz($jpgs),$ji); $ji['validation_status']='VALID'; $ji['blocking_errors']=[]; $ji['photos'][0]['width']=16; $ji['photos'][0]['height']=12; $ji['photos'][0]['file_size_bytes']=strlen(array_values($jpgs)[0]); $ji['total_jpeg_bytes']=$ji['photos'][0]['file_size_bytes']; merr(fn()=>auto_photo_bundle_materialize_from_row($jr,['index'=>$ji,'dry_run'=>true]),$code,$msg); }

[$sr,$sb]=minst(mtgz(['capture/photos/frame_000001.jpg'=>mjpg()]),$si); auto_photo_bundle_materialize_from_row($sr,['index'=>$si]); $orig=$sb.'/photos/frame_000001.jpg'; $external=sys_get_temp_dir().'/apbm_external_'.bin2hex(random_bytes(4)).'.jpg'; copy($orig,$external); unlink($orig); symlink($external,$orig); merr(fn()=>auto_photo_bundle_materialize_from_row($sr,['index'=>$si]),'existing_materialization_mismatch','existing JPEG symlink rejected');
[$gr,$gb]=minst(mtgz(['capture/photos/frame_000001.jpg'=>mjpg()]),$gi); auto_photo_bundle_materialize_from_row($gr,['index'=>$gi]); $gm=json_decode(file_get_contents($gb.'/materialization.json'),true); $ghost=$gm['photos'][0]; $ghost['filename']='ghost.jpg'; $ghost['archive_path']='capture/photos/ghost.jpg'; $gm['photos'][]=$ghost; $gm['photos_count']=1; file_put_contents($gb.'/materialization.json', json_encode($gm)); merr(fn()=>auto_photo_bundle_materialize_from_row($gr,['index'=>$gi]),'existing_materialization_mismatch','ghost materialization entry rejected');
[$er,$eb]=minst(mtgz(['capture/photos/frame_000001.jpg'=>mjpg()]),$ei); auto_photo_bundle_materialize_from_row($er,['index'=>$ei]); $em=json_decode(file_get_contents($eb.'/materialization.json'),true); $em['total_bytes']++; file_put_contents($eb.'/materialization.json',json_encode($em)); $matSha=hash_file('sha256',$eb.'/materialization.json'); $jpegShas=[]; foreach (glob($eb.'/photos/*.jpg') as $jpeg) $jpegShas[basename($jpeg)]=hash_file('sha256',$jpeg); merr(fn()=>auto_photo_bundle_materialize_from_row($er,['index'=>$ei]),'existing_materialization_mismatch','mismatching materialization retained'); mtassert(is_file($eb.'/materialization.json') && hash_file('sha256',$eb.'/materialization.json')===$matSha && array_map(fn($p)=>hash_file('sha256',$eb.'/photos/'.$p),array_keys($jpegShas))===array_values($jpegShas), 'mismatching state is not deleted');
[$isr,$isb]=minst(mtgz(),$isi); $outsideIndex=sys_get_temp_dir().'/apbm_index_link_'.bin2hex(random_bytes(4)).'.json'; copy($isb.'/index.json',$outsideIndex); unlink($isb.'/index.json'); symlink($outsideIndex,$isb.'/index.json'); merr(fn()=>auto_photo_bundle_materialize_from_row($isr,['dry_run'=>true]),'unsafe_index_file','index.json symlink rejected');
[$msr,$msb]=minst(mtgz(),$msi); auto_photo_bundle_materialize_from_row($msr,['index'=>$msi]); $outsideMat=sys_get_temp_dir().'/apbm_mat_link_'.bin2hex(random_bytes(4)).'.json'; copy($msb.'/materialization.json',$outsideMat); unlink($msb.'/materialization.json'); symlink($outsideMat,$msb.'/materialization.json'); merr(fn()=>auto_photo_bundle_materialize_from_row($msr,['index'=>$msi]),'existing_materialization_mismatch','materialization.json symlink rejected');
[$dsr,$dsb]=minst(mtgz(),$dsi); symlink('/definitely/missing/photos',$dsb.'/photos'); merr(fn()=>auto_photo_bundle_materialize_from_row($dsr,['index'=>$dsi]),'existing_materialization_mismatch','dangling photos symlink rejected');
[$lsr,$lsb]=minst(mtgz(),$lsi); $outsideLock=sys_get_temp_dir().'/apbm_lock_link_'.bin2hex(random_bytes(4)); file_put_contents($outsideLock,''); symlink($outsideLock,$lsb.'/.materialize.lock'); merr(fn()=>auto_photo_bundle_materialize_from_row($lsr,['index'=>$lsi]),'unsafe_materialization_lock','materialization lock symlink rejected');
[$bsr,$bsb,$bsa]=minst(mtgz(),$bsi); $outsideBase=sys_get_temp_dir().'/apbm_base_link_'.bin2hex(random_bytes(4)); mkdir($outsideBase); copy($bsb.'/index.json',$outsideBase.'/index.json'); auto_photo_bundle_rrmdir($bsb); symlink($outsideBase,$bsb); merr(fn()=>auto_photo_bundle_materialize_from_row($bsr,['dry_run'=>true]),'unsafe_materialization_base_dir','base directory symlink rejected in dry-run'); merr(fn()=>auto_photo_bundle_materialize_from_row($bsr),'unsafe_materialization_base_dir','base directory symlink rejected in materialization'); mtassert(!file_exists($outsideBase.'/.materialize.lock') && glob($outsideBase.'/.materialization.stage.*')===[] && !file_exists($outsideBase.'/photos') && !file_exists($outsideBase.'/materialization.json'),'path escape leaves external directory untouched');
[$chr,$chb]=minst(mtgz(),$chi); merr(fn()=>auto_photo_bundle_materialize_from_row($chr,['index'=>$chi,'dry_run'=>true,'inject_archive_change_after_scan'=>true]),'archive_changed_during_materialization','archive changed during dry-run');
[$pr,$pb]=minst(mtgz(),$pi); merr(fn()=>auto_photo_bundle_materialize_from_row($pr,['index'=>$pi,'inject_partial_write_after_bytes'=>10]),'photo_write_failed','partial disk write'); mtassert(!is_dir($pb.'/photos') && glob($pb.'/.materialization.stage.*')===[], 'temporary cleanup');
[$ar,$ab]=minst(mtgz(),$ai); $idxBefore=hash_file('sha256',$ab.'/index.json'); merr(fn()=>auto_photo_bundle_materialize_from_row($ar,['index'=>$ai,'inject_materialization_publish_failure'=>true]),'materialization_rename_failed','atomic rollback after photos rename'); mtassert(!is_dir($ab.'/photos') && !is_file($ab.'/materialization.json') && glob($ab.'/.materialization.stage.*')===[] && hash_file('sha256',$ab.'/index.json')===$idxBefore, 'rollback cleanup');
[$cr,$cb]=minst(mtgz(),$ci); $first=auto_photo_bundle_materialize_from_row($cr,['index'=>$ci]); $second=auto_photo_bundle_materialize_from_row($cr,['index'=>$ci]); mtassert(($first['idempotent']??false)===false && ($second['idempotent']??false)===true, 'sequential idempotency');

[$fr,$fb]=minst(mtgz(),$fi); if (function_exists('pcntl_fork')) { $outA=$fb.'/a.json'; $outB=$fb.'/b.json'; $pid=pcntl_fork(); if ($pid===0) { $ra=auto_photo_bundle_materialize_from_row($fr,['inject_lock_delay_ms'=>500]); file_put_contents($outA,json_encode($ra)); exit(0); } usleep(50000); $pid2=pcntl_fork(); if ($pid2===0) { $rb=auto_photo_bundle_materialize_from_row($fr); file_put_contents($outB,json_encode($rb)); exit(0); } pcntl_waitpid($pid,$st1); pcntl_waitpid($pid2,$st2); $ra=json_decode(file_get_contents($outA),true); $rb=json_decode(file_get_contents($outB),true); mtassert(($ra['idempotent']??null)===false && ($rb['idempotent']??null)===true && glob($fb.'/.materialization.stage.*')===[] && is_dir($fb.'/photos') && is_file($fb.'/materialization.json'), 'real parallel lock/idempotency'); } else { mtassert(false, 'pcntl_fork unavailable for real parallel lock/idempotency'); }
[$lr100,$lb100]=minst(mtgz_large_stream(100,1024*1024),$li100); $lim=['max_jpeg_count'=>150,'max_single_jpeg_bytes'=>2*1024*1024,'max_member_bytes'=>2*1024*1024,'max_declared_unpacked_bytes'=>200*1024*1024,'max_jsonl_bytes'=>1024*1024]; $ldr=auto_photo_bundle_materialize_from_row($lr100,['index'=>$li100,'dry_run'=>true,'limits'=>$lim]); $lmr=auto_photo_bundle_materialize_from_row($lr100,['index'=>$li100,'limits'=>$lim]); mtassert($ldr['photos_count']===100 && $lmr['photos_count']===100, '100x1MiB streaming dry-run/materialization');
[$or,$ob]=minst(mtgz(),$oi); putenv('AUTO_PHOTO_BUNDLE_TEST_MODE=false'); merr(fn()=>auto_photo_bundle_materialize_from_row($or,['index'=>$oi,'dry_run'=>true]),'index_option_forbidden','production index override forbidden'); merr(fn()=>auto_photo_bundle_materialize_from_row($or,['inject_lock_delay_ms'=>1]),'inject_lock_delay_ms_forbidden','production injection hook forbidden'); putenv('AUTO_PHOTO_BUNDLE_TEST_MODE=true');

echo $failures === 0 ? "PASS\n" : "FAILURES: $failures\n"; exit($failures === 0 ? 0 : 1);
