<?php
declare(strict_types=1);
$root=sys_get_temp_dir().'/sfm_cleanup_'.bin2hex(random_bytes(8));
putenv('SFM_CLEANUP_TEST_MODE=true'); putenv('SFM_CLEANUP_TEST_WEB_OUTPUT_BASE='.$root);
require_once __DIR__.'/../remote_station/sfm_cleanup.php';
function check(bool $ok,string $message): void { if(!$ok)throw new RuntimeException($message); }
function job(int $id,string $type='EXTRACT_FRAMES'): array { return ['remote_job_id'=>$id,'job_type'=>$type]; }
function video(int $id,string $contents='safe'): string { global $root; $path=$root.'/job_'.$id.'/normalized/source_safe.mp4'; mkdir(dirname($path),0700,true); file_put_contents($path,$contents); return $path; }
function fails(callable $fn,string $expected): void { try{$fn();}catch(RuntimeException $e){check($e->getMessage()===$expected,'expected '.$expected.', got '.$e->getMessage());return;} throw new RuntimeException('expected failure '.$expected); }
function remove_tree(string $path): void { if(!file_exists($path)&&!is_link($path))return; foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST) as $f)$f->isDir()&&!$f->isLink()?rmdir($f->getPathname()):unlink($f->getPathname()); rmdir($path); }
$target=$original=null;
try {
    mkdir($root,0700,true); check(sfm_remote_cleanup_web_output_base()===$root,'test output root resolved'); $id=1;
    $file=video($id,'12345'); $dry=sfm_remote_cleanup_local_normalized_video([job($id)],true); check($dry['paths'][0]['status']==='WOULD_DELETE' && $dry['would_free_bytes']===5 && is_file($file),'dry run');
    $deleted=sfm_remote_cleanup_local_normalized_video([job($id)],false); check(!file_exists($file) && $deleted['freed_bytes']===5,'delete only source_safe'); check(sfm_remote_cleanup_local_normalized_video([job($id)],false)['paths'][0]['status']==='ALREADY_ABSENT','missing idempotent');
    $file=video(++$id); $called=$localCalled=false; $GLOBALS['sfm_cleanup_test_station_callback']=function() use (&$called): array {$called=true; throw new RuntimeException('station cleanup failed');}; $GLOBALS['sfm_cleanup_test_after_local_plan']=function() use (&$localCalled): void {$localCalled=true;}; fails(fn()=>sfm_remote_cleanup_run_station_and_local_cleanup([job($id)],[$id],false),'station cleanup failed'); unset($GLOBALS['sfm_cleanup_test_station_callback'],$GLOBALS['sfm_cleanup_test_after_local_plan']); check($called && !$localCalled && is_file($file) && file_get_contents($file)==='safe','station failure skips local execute');
    $file=video(++$id); $events=[]; $GLOBALS['sfm_cleanup_test_station_callback']=function() use (&$events): array {$events[]='station'; return ['freed_bytes'=>0,'paths'=>[]];}; $GLOBALS['sfm_cleanup_test_after_local_plan']=function() use (&$events): void {$events[]='local';}; sfm_remote_cleanup_run_station_and_local_cleanup([job($id)],[$id],false); unset($GLOBALS['sfm_cleanup_test_station_callback'],$GLOBALS['sfm_cleanup_test_after_local_plan']); check($events===['station','local'] && !file_exists($file),'station then local');
    $target=tempnam(sys_get_temp_dir(),'sfm-target-'); file_put_contents($target,'target'); $file=video(++$id); unlink($file); symlink($target,$file); fails(fn()=>sfm_remote_cleanup_local_normalized_video([job($id)],false),'unsafe_local_normalized_video'); check(file_get_contents($target)==='target','file symlink target retained');
    $jobRoot=$root.'/job_'.(++$id); symlink(dirname($target),$jobRoot); fails(fn()=>sfm_remote_cleanup_local_normalized_video([job($id)],false),'unsafe_local_normalized_video');
    $jobRoot=$root.'/job_'.(++$id); mkdir($jobRoot,0700,true); symlink(dirname($target),$jobRoot.'/normalized'); fails(fn()=>sfm_remote_cleanup_local_normalized_video([job($id)],false),'unsafe_local_normalized_video');
    $jobRoot=$root.'/job_'.(++$id); mkdir($jobRoot.'/normalized/source_safe.mp4',0700,true); fails(fn()=>sfm_remote_cleanup_local_normalized_video([job($id)],false),'unsafe_local_normalized_video'); rmdir($jobRoot.'/normalized/source_safe.mp4'); if(function_exists('posix_mkfifo')) { posix_mkfifo($jobRoot.'/normalized/source_safe.mp4',0600); fails(fn()=>sfm_remote_cleanup_local_normalized_video([job($id)],false),'unsafe_local_normalized_video'); unlink($jobRoot.'/normalized/source_safe.mp4'); }
    $file=video(++$id,'old'); $GLOBALS['sfm_cleanup_test_after_local_plan']=function(array $plan): void { file_put_contents($plan[0]['path'],'replacement'); }; fails(fn()=>sfm_remote_cleanup_local_normalized_video([job($id)],false),'local_normalized_video_changed'); unset($GLOBALS['sfm_cleanup_test_after_local_plan']); check(file_get_contents($file)==='replacement','replacement retained');
    $file=video(++$id,'safe'); file_put_contents(dirname($file).'/keep.txt','keep'); sfm_remote_cleanup_local_normalized_video([job($id)],false); check(is_file(dirname($file).'/keep.txt') && is_dir(dirname($file)),'keep prevents rmdir');
    $file=video(++$id,'safe'); $normal=dirname($file); sfm_remote_cleanup_local_normalized_video([job($id)],false); check(!is_dir($normal),'empty normalized removed');
    $file=video(++$id,'safe'); check(sfm_remote_cleanup_local_normalized_video([job($id,'COLMAP_SPARSE')],false)['paths']===[] && is_file($file),'non extract ignored'); check(count(sfm_remote_cleanup_local_normalized_video([job($id),job($id)],true)['paths'])===1,'duplicate handled once');
    $original=tempnam(sys_get_temp_dir(),'sfm-original-'); file_put_contents($original,'original'); $sha=hash_file('sha256',$original); $jobRoot=dirname(dirname($file)); file_put_contents($jobRoot.'/result.json','result'); mkdir($jobRoot.'/frames',0700,true); file_put_contents($jobRoot.'/frames/a.jpg','frame'); mkdir($jobRoot.'/sparse',0700,true); file_put_contents($jobRoot.'/sparse/a.ply','ply'); file_put_contents($jobRoot.'/logs.txt','log'); sfm_remote_cleanup_local_normalized_video([job($id)],false); check(hash_file('sha256',$original)===$sha && is_file($jobRoot.'/result.json') && is_file($jobRoot.'/frames/a.jpg') && is_file($jobRoot.'/sparse/a.ply') && is_file($jobRoot.'/logs.txt'),'original and derived artifacts unchanged');
    echo "PASS sfm local normalized video cleanup\n";
} finally { unset($GLOBALS['sfm_cleanup_test_station_callback'],$GLOBALS['sfm_cleanup_test_after_local_plan']); remove_tree($root); if($target!==null)@unlink($target); if($original!==null)@unlink($original); }
